名字 = "emby-proxy"
主要的 = "worker.js"
compatibility_date = "2025-05-15"

[vars]
BASE_DOMAIN = "example.com"
ADMIN_TOKEN = "liu1752256014"
CF_API_TOKEN = ""
CF_ZONE_ID = ""
CF_ACCOUNT_ID = ""
DNS_RECORD_NAME = "emby"

[[d1_databases]]
封皮 = "DB"
database_name = "emby-proxy-db"
database_id = "cc126150-2d91-4b86-aaa2-9498498b6ace"
